name: Build and Release

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npx tsx scripts/build.ts

            - name: Create Debug Tag
              id: create_tag
              run: |
                  TIMESTAMP=$(date +%Y%m%d-%H%M%S)
                  echo "tag_name=debug-${TIMESTAMP}" >> $GITHUB_OUTPUT

            - name: Create Git Tag
              run: |
                  git tag ${{ steps.create_tag.outputs.tag_name }}
                  git push origin ${{ steps.create_tag.outputs.tag_name }}

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.create_tag.outputs.tag_name }}
                  release_name: Debug Release ${{ steps.create_tag.outputs.tag_name }}
                  draft: false
                  prerelease: true

            - name: Upload Release Assets
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  for file in dist/*; do
                    if [ -f "$file" ]; then
                      echo "Uploading $file..."
                      gh release upload ${{ steps.create_tag.outputs.tag_name }} "$file"
                    fi
                  done
